//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Address.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Address.Language.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe una dirección con esa llave..
        /// </summary>
        public static string AddressExist {
            get {
                return ResourceManager.GetString("AddressExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La llave de direcciones no puede estar vacía..
        /// </summary>
        public static string AddressKeyNotEmpty {
            get {
                return ResourceManager.GetString("AddressKeyNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección es nula..
        /// </summary>
        public static string AddressNull {
            get {
                return ResourceManager.GetString("AddressNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado o provincia no puede estar vacía..
        /// </summary>
        public static string AddressStateNull {
            get {
                return ResourceManager.GetString("AddressStateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País no puede estar vacío..
        /// </summary>
        public static string CountryNull {
            get {
                return ResourceManager.GetString("CountryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de efecto no puede estar vacía..
        /// </summary>
        public static string EffectiveDateNull {
            get {
                return ResourceManager.GetString("EffectiveDateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propietario no puede ser vacío o cero..
        /// </summary>
        public static string OwnerNull {
            get {
                return ResourceManager.GetString("OwnerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llave de teléfono con formato erróneo..
        /// </summary>
        public static string PhoneKeyBadFormatOrOverflow {
            get {
                return ResourceManager.GetString("PhoneKeyBadFormatOrOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llave de teléfono no puede estar vacía o igual a cero..
        /// </summary>
        public static string PhoneKeyNull {
            get {
                return ResourceManager.GetString("PhoneKeyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono no puede estar vacío..
        /// </summary>
        public static string PhoneNull {
            get {
                return ResourceManager.GetString("PhoneNull", resourceCulture);
            }
        }
    }
}
